apiVersion: v1
kind: Service
metadata:
  name: {{ include "pygbsentry.fullname" . }}-frontend
  labels:
    {{- include "pygbsentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "pygbsentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
