"""initial schema from existing models

Revision ID: 4bbb649f0063
Revises: 
Create Date: 2026-04-21 09:46:35.901036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbb649f0063'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_sources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('stream_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('gb_enabled', sa.Boolean(), nullable=True),
    sa.Column('gb_id', sa.String(length=64), nullable=True),
    sa.Column('gb_name', sa.String(length=128), nullable=True),
    sa.Column('gb_parent_gb_id', sa.String(length=64), nullable=True),
    sa.Column('gb_resource_id', sa.String(length=32), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_sources_enabled'), 'access_sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_access_sources_gb_enabled'), 'access_sources', ['gb_enabled'], unique=False)
    op.create_index(op.f('ix_access_sources_gb_id'), 'access_sources', ['gb_id'], unique=False)
    op.create_index(op.f('ix_access_sources_gb_resource_id'), 'access_sources', ['gb_resource_id'], unique=False)
    op.create_index(op.f('ix_access_sources_protocol'), 'access_sources', ['protocol'], unique=False)
    op.create_index(op.f('ix_access_sources_tenant_id'), 'access_sources', ['tenant_id'], unique=False)
    op.create_table('alarm_link_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('min_priority', sa.Integer(), nullable=True),
    sa.Column('max_priority', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=8), nullable=True),
    sa.Column('end_time', sa.String(length=8), nullable=True),
    sa.Column('days', sa.String(length=32), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('link_record', sa.Boolean(), nullable=True),
    sa.Column('link_wall', sa.Boolean(), nullable=True),
    sa.Column('link_notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_link_rules_enabled'), 'alarm_link_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_alarm_link_rules_organization_id'), 'alarm_link_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alarm_link_rules_tenant_id'), 'alarm_link_rules', ['tenant_id'], unique=False)
    op.create_table('alarm_notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('alarm_id', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_notifications_alarm_id'), 'alarm_notifications', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_channel'), 'alarm_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_channel_id'), 'alarm_notifications', ['channel_id'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_device_id'), 'alarm_notifications', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_sent_at'), 'alarm_notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_status'), 'alarm_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_alarm_notifications_tenant_id'), 'alarm_notifications', ['tenant_id'], unique=False)
    op.create_table('app_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('plugin_id', sa.String(length=64), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('log_type', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_logs_app_version'), 'app_logs', ['app_version'], unique=False)
    op.create_index(op.f('ix_app_logs_created_at'), 'app_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_logs_log_type'), 'app_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_app_logs_platform'), 'app_logs', ['platform'], unique=False)
    op.create_index(op.f('ix_app_logs_plugin_id'), 'app_logs', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_app_logs_tenant_id'), 'app_logs', ['tenant_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=True, comment='所属组织，用于分级分权'),
    sa.Column('gb_id', sa.String(length=20), nullable=False, comment='国标编码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='设备名称'),
    sa.Column('transport', sa.String(length=10), nullable=True, comment='传输协议: UDP/TCP'),
    sa.Column('ip_addr', sa.String(length=64), nullable=True, comment='设备IP'),
    sa.Column('port', sa.Integer(), nullable=True, comment='信令端口'),
    sa.Column('manufacturer', sa.String(length=64), nullable=True, comment='厂商'),
    sa.Column('model', sa.String(length=64), nullable=True, comment='型号'),
    sa.Column('firmware', sa.String(length=64), nullable=True, comment='固件版本'),
    sa.Column('status', sa.Integer(), nullable=True, comment='0: Offline, 1: Online'),
    sa.Column('last_keepalive', sa.DateTime(), nullable=True, comment='最后心跳时间'),
    sa.Column('register_time', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.Column('expires', sa.Integer(), nullable=True, comment='注册有效期'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='SIP密码'),
    sa.Column('domain', sa.String(length=64), nullable=True, comment='SIP域'),
    sa.Column('charset', sa.String(length=10), nullable=True, comment='字符集: UTF-8/GB2312'),
    sa.Column('ssrc_check', sa.Boolean(), nullable=True, comment='是否检查SSRC'),
    sa.Column('geo_coord_sys', sa.String(length=10), nullable=True, comment='地理坐标系: WGS84/GCJ02'),
    sa.Column('as_message_channel', sa.Boolean(), nullable=True, comment='作为消息通道'),
    sa.Column('heartbeat_interval', sa.Integer(), nullable=True, comment='心跳间隔'),
    sa.Column('heartbeat_count', sa.Integer(), nullable=True, comment='心跳超时次数'),
    sa.Column('keepalive_interval', sa.Integer(), nullable=True, comment='Keepalive间隔(秒)，兼容旧字段别名'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_gb_id'), 'assets', ['gb_id'], unique=True)
    op.create_index(op.f('ix_assets_organization_id'), 'assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assets_tenant_id'), 'assets', ['tenant_id'], unique=False)
    op.create_table('billing_plans',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('max_channels', sa.Integer(), nullable=True),
    sa.Column('plugin_entitlements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_plans_code'), 'billing_plans', ['code'], unique=True)
    op.create_index(op.f('ix_billing_plans_is_active'), 'billing_plans', ['is_active'], unique=False)
    op.create_table('cloud_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('node_ids', sa.JSON(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_clusters_enabled'), 'cloud_clusters', ['enabled'], unique=False)
    op.create_index(op.f('ix_cloud_clusters_tenant_id'), 'cloud_clusters', ['tenant_id'], unique=False)
    op.create_table('command_instructions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False, comment='会商会话ID，通常为 alarm_id'),
    sa.Column('content', sa.Text(), nullable=False, comment='指令内容'),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_instructions_session_id'), 'command_instructions', ['session_id'], unique=False)
    op.create_index(op.f('ix_command_instructions_user_id'), 'command_instructions', ['user_id'], unique=False)
    op.create_table('command_participants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_participants_session_id'), 'command_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_command_participants_user_id'), 'command_participants', ['user_id'], unique=False)
    op.create_table('command_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('alarm_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_sessions_alarm_id'), 'command_sessions', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_command_sessions_status'), 'command_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_command_sessions_tenant_id'), 'command_sessions', ['tenant_id'], unique=False)
    op.create_table('config_drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('draft_id', sa.String(length=32), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_drafts_draft_id'), 'config_drafts', ['draft_id'], unique=True)
    op.create_table('config_revisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_revisions_revision'), 'config_revisions', ['revision'], unique=False)
    op.create_table('device_clusters',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_clusters_tenant_id'), 'device_clusters', ['tenant_id'], unique=False)
    op.create_table('device_positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=20), nullable=False, comment='设备国标ID'),
    sa.Column('channel_id', sa.String(length=20), nullable=True, comment='通道国标ID'),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False, comment='定位时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_positions_channel_id'), 'device_positions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_device_positions_device_id'), 'device_positions', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_positions_time'), 'device_positions', ['time'], unique=False)
    op.create_table('ffmpeg_cmds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cmd_template', sa.Text(), nullable=False),
    sa.Column('enabled', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ffmpeg_cmds_created_at'), 'ffmpeg_cmds', ['created_at'], unique=False)
    op.create_index(op.f('ix_ffmpeg_cmds_tenant_id'), 'ffmpeg_cmds', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ffmpeg_cmds_updated_at'), 'ffmpeg_cmds', ['updated_at'], unique=False)
    op.create_table('ip_blacklist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_blacklist_ip'), 'ip_blacklist', ['ip'], unique=True)
    op.create_table('map_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('vector_tile_url', sa.String(length=512), nullable=True, comment='MVT Vector Tile URL Template'),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('zoom_level', sa.Integer(), nullable=True),
    sa.Column('min_zoom', sa.Integer(), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_config_tenant_id'), 'map_config', ['tenant_id'], unique=False)
    op.create_table('media_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('public_ip', sa.String(length=64), nullable=True, comment='公网IP'),
    sa.Column('stream_ip', sa.String(length=128), nullable=True, comment='流媒体对外访问地址（IP或域名）'),
    sa.Column('hook_base_url', sa.String(length=255), nullable=True, comment='ZLM Hook Base URL（可选覆盖）'),
    sa.Column('hook_ip', sa.String(length=64), nullable=True, comment='Hook 回调连通用 IP（可选）'),
    sa.Column('sdp_ip', sa.String(length=64), nullable=True, comment='SDP 对外 IP（NAT 场景可选）'),
    sa.Column('http_port', sa.Integer(), nullable=True),
    sa.Column('https_port', sa.Integer(), nullable=True, comment='HTTPS 端口（可选）'),
    sa.Column('rtsp_port', sa.Integer(), nullable=True),
    sa.Column('rtsps_port', sa.Integer(), nullable=True, comment='RTSPS 端口（可选）'),
    sa.Column('rtmp_port', sa.Integer(), nullable=True),
    sa.Column('rtmps_port', sa.Integer(), nullable=True, comment='RTMPS 端口（可选）'),
    sa.Column('rtp_proxy_port', sa.Integer(), nullable=True),
    sa.Column('rtp_port_mode', sa.String(length=16), nullable=True, comment='收流端口模式：single|range'),
    sa.Column('rtp_port_range_start', sa.Integer(), nullable=True, comment='收流端口范围起始（range 模式）'),
    sa.Column('rtp_port_range_end', sa.Integer(), nullable=True, comment='收流端口范围结束（range 模式）'),
    sa.Column('record_mgr_port', sa.Integer(), nullable=True, comment='录像管理服务端口（可选）'),
    sa.Column('record_file_second', sa.Integer(), nullable=True, comment='录像分片时长秒（0=使用全局默认）'),
    sa.Column('record_sample_ms', sa.Integer(), nullable=True, comment='录像采样间隔毫秒（0=使用全局默认）'),
    sa.Column('protocol_mp4_max_second', sa.Integer(), nullable=True, comment='MP4单文件最大时长秒（0=使用全局默认）'),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('zlm_ssl_merged_pem', sa.Text(), nullable=True, comment='ZLM HTTPS 合并 PEM（私钥+证书链，见官方文档）'),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True, comment='最后一次收到 hook/keepalive 的时间'),
    sa.Column('last_probe_error', sa.String(length=512), nullable=True, comment='最近一次主动探测错误（可选）'),
    sa.Column('is_embedded', sa.Boolean(), nullable=True, comment='是否为内置节点'),
    sa.Column('auto_config_enabled', sa.Boolean(), nullable=True, comment='是否自动配置媒体服务（内置 ZLM）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_port_leases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('media_server_id', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('stream_session_id', sa.String(length=32), nullable=True),
    sa.Column('leased_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_server_id', 'port', name='uq_media_port_leases_server_port')
    )
    op.create_index(op.f('ix_media_port_leases_media_server_id'), 'media_port_leases', ['media_server_id'], unique=False)
    op.create_index(op.f('ix_media_port_leases_stream_session_id'), 'media_port_leases', ['stream_session_id'], unique=False)
    op.create_table('network_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_metrics_created_at'), 'network_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_network_metrics_metric'), 'network_metrics', ['metric'], unique=False)
    op.create_index(op.f('ix_network_metrics_tenant_id'), 'network_metrics', ['tenant_id'], unique=False)
    op.create_table('operation_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_audits_module'), 'operation_audits', ['module'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organizations_tenant_id'), 'organizations', ['tenant_id'], unique=False)
    op.create_table('parent_platforms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('server_gb_id', sa.String(length=20), nullable=False),
    sa.Column('server_ip', sa.String(length=64), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.String(length=8), nullable=True),
    sa.Column('client_gb_id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_keepalive', sa.DateTime(), nullable=True),
    sa.Column('register_interval', sa.Integer(), nullable=True),
    sa.Column('keepalive_interval', sa.Integer(), nullable=True),
    sa.Column('catalog_batch_size', sa.Integer(), nullable=True, comment='目录分组推送每批通道数，0=不分组一次全推'),
    sa.Column('catalog_push_delay_seconds', sa.Integer(), nullable=True, comment='注册成功后延迟多少秒再首次推送目录，0=立即推送'),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_gb_id')
    )
    op.create_index(op.f('ix_parent_platforms_tenant_id'), 'parent_platforms', ['tenant_id'], unique=False)
    op.create_table('platform_catalog_resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('virtual_gb_id', sa.String(length=64), nullable=True, comment='推给上级时的伪装ID'),
    sa.Column('virtual_name', sa.String(length=128), nullable=True, comment='推给上级时的伪装名称'),
    sa.Column('virtual_parent_id', sa.String(length=64), nullable=True, comment='挂载的上级虚拟目录ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'resource_id', name='uq_platform_catalog')
    )
    op.create_index(op.f('ix_platform_catalog_resources_platform_id'), 'platform_catalog_resources', ['platform_id'], unique=False)
    op.create_index(op.f('ix_platform_catalog_resources_resource_id'), 'platform_catalog_resources', ['resource_id'], unique=False)
    op.create_table('platform_runtimes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('platform_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_runtimes_platform_id'), 'platform_runtimes', ['platform_id'], unique=False)
    op.create_index(op.f('ix_platform_runtimes_tenant_id'), 'platform_runtimes', ['tenant_id'], unique=False)
    op.create_table('plugin_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('plugin_id', sa.String(length=64), nullable=False),
    sa.Column('plugin_name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('pay_channel', sa.String(length=32), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('callback_payload', sa.Text(), nullable=True),
    sa.Column('license_data', sa.Text(), nullable=True),
    sa.Column('billing_period', sa.String(length=16), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=24), nullable=True),
    sa.Column('upgrade_policy', sa.String(length=24), nullable=True),
    sa.Column('version_major', sa.String(length=16), nullable=True),
    sa.Column('maintenance_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_orders_order_no'), 'plugin_orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_plugin_orders_plugin_id'), 'plugin_orders', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_orders_status'), 'plugin_orders', ['status'], unique=False)
    op.create_index(op.f('ix_plugin_orders_tenant_id'), 'plugin_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_plugin_orders_user_id'), 'plugin_orders', ['user_id'], unique=False)
    op.create_table('publish_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('publish_id', sa.String(length=32), nullable=False),
    sa.Column('from_revision', sa.Integer(), nullable=False),
    sa.Column('to_revision', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_records_publish_id'), 'publish_records', ['publish_id'], unique=True)
    op.create_table('record_schedule_runtimes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('schedule_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('forced_mode', sa.String(length=8), nullable=True),
    sa.Column('forced_until', sa.DateTime(), nullable=True),
    sa.Column('desired_recording', sa.Boolean(), nullable=True),
    sa.Column('is_recording', sa.Boolean(), nullable=True),
    sa.Column('last_eval_at', sa.DateTime(), nullable=True),
    sa.Column('last_stream_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('last_action', sa.String(length=32), nullable=True),
    sa.Column('last_action_ok', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_media_node_id', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_schedule_runtimes_created_at'), 'record_schedule_runtimes', ['created_at'], unique=False)
    op.create_index(op.f('ix_record_schedule_runtimes_resource_id'), 'record_schedule_runtimes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_record_schedule_runtimes_schedule_id'), 'record_schedule_runtimes', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_record_schedule_runtimes_tenant_id'), 'record_schedule_runtimes', ['tenant_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False, comment='行政区划代码，如 110000'),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True, comment='上级区域ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='层级 0省 1市 2区县'),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_parent_id'), 'regions', ['parent_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permission_codes', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=False)
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_roles_updated_at'), 'roles', ['updated_at'], unique=False)
    op.create_table('rtp_receive_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.String(length=32), nullable=True),
    sa.Column('app', sa.String(length=64), nullable=True),
    sa.Column('stream_id', sa.String(length=128), nullable=False),
    sa.Column('ssrc', sa.String(length=64), nullable=True),
    sa.Column('tcp_mode', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rtp_receive_tasks_created_at'), 'rtp_receive_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_lease_id'), 'rtp_receive_tasks', ['lease_id'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_node_id'), 'rtp_receive_tasks', ['node_id'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_status'), 'rtp_receive_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_stream_id'), 'rtp_receive_tasks', ['stream_id'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_tenant_id'), 'rtp_receive_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_rtp_receive_tasks_updated_at'), 'rtp_receive_tasks', ['updated_at'], unique=False)
    op.create_table('sip_trace_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('platform_id', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sip_trace_events_channel_id'), 'sip_trace_events', ['channel_id'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_created_at'), 'sip_trace_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_device_id'), 'sip_trace_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_event'), 'sip_trace_events', ['event'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_platform_id'), 'sip_trace_events', ['platform_id'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_tenant_id'), 'sip_trace_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sip_trace_events_trace_id'), 'sip_trace_events', ['trace_id'], unique=False)
    op.create_table('structured_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('source_plugin', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_events_channel_id'), 'structured_events', ['channel_id'], unique=False)
    op.create_index(op.f('ix_structured_events_created_at'), 'structured_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_structured_events_device_id'), 'structured_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_structured_events_event_time'), 'structured_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_structured_events_event_type'), 'structured_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_structured_events_source_plugin'), 'structured_events', ['source_plugin'], unique=False)
    op.create_index(op.f('ix_structured_events_tenant_id'), 'structured_events', ['tenant_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('setting_value', sa.String(length=2000), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('tenant_branding',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=16), nullable=True),
    sa.Column('welcome_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_branding_tenant_id'), 'tenant_branding', ['tenant_id'], unique=True)
    op.create_table('tenant_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('plan_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('machine_code', sa.String(length=128), nullable=True),
    sa.Column('machine_code_registered_at', sa.DateTime(), nullable=True),
    sa.Column('extra_machine_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_machine_code'), 'tenant_subscriptions', ['machine_code'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_plan_code'), 'tenant_subscriptions', ['plan_code'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_status'), 'tenant_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_subscriptions_tenant_id'), 'tenant_subscriptions', ['tenant_id'], unique=True)
    op.create_table('user_api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('allowed_ips', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_api_keys_key_prefix'), 'user_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_user_api_keys_tenant_id'), 'user_api_keys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alarms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('alarm_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['assets.gb_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_channel_id'), 'alarms', ['channel_id'], unique=False)
    op.create_index(op.f('ix_alarms_device_id'), 'alarms', ['device_id'], unique=False)
    op.create_index(op.f('ix_alarms_status'), 'alarms', ['status'], unique=False)
    op.create_index(op.f('ix_alarms_tenant_id'), 'alarms', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alarms_time'), 'alarms', ['time'], unique=False)
    op.create_table('asset_maintenances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('maintenance_type', sa.String(length=32), nullable=True, comment='routine=例行, repair=维修, upgrade=升级, replace=更换'),
    sa.Column('maintenance_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_maintenances_asset_id'), 'asset_maintenances', ['asset_id'], unique=False)
    op.create_table('asset_stream_health',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('last_mode', sa.String(length=32), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=False),
    sa.Column('success_total', sa.Integer(), nullable=False),
    sa.Column('fail_total', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('auto_switch_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_stream_health_asset_id'), 'asset_stream_health', ['asset_id'], unique=True)
    op.create_table('asset_stream_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('stream_mode', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_stream_policies_asset_id'), 'asset_stream_policies', ['asset_id'], unique=True)
    op.create_table('device_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('catalog_cycle_seconds', sa.Integer(), nullable=True),
    sa.Column('last_catalog_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_catalog_sync_ok', sa.Integer(), nullable=True),
    sa.Column('last_catalog_sync_error', sa.String(length=500), nullable=True),
    sa.Column('mobile_position_enabled', sa.Integer(), nullable=True),
    sa.Column('mobile_position_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('mobile_position_renew_seconds', sa.Integer(), nullable=True),
    sa.Column('last_mobile_position_subscribe_at', sa.DateTime(), nullable=True),
    sa.Column('last_mobile_position_subscribe_ok', sa.Integer(), nullable=True),
    sa.Column('last_mobile_position_subscribe_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_subscriptions_asset_id'), 'device_subscriptions', ['asset_id'], unique=True)
    op.create_index(op.f('ix_device_subscriptions_created_at'), 'device_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_subscriptions_tenant_id'), 'device_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_subscriptions_updated_at'), 'device_subscriptions', ['updated_at'], unique=False)
    op.create_table('platform_subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('platform_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('expires_seconds', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_subscribe_at', sa.DateTime(), nullable=True),
    sa.Column('last_notify_at', sa.DateTime(), nullable=True),
    sa.Column('last_addr', sa.String(length=128), nullable=True),
    sa.Column('last_transport', sa.String(length=8), nullable=True),
    sa.Column('last_call_id', sa.String(length=128), nullable=True),
    sa.Column('remote_from_tag', sa.String(length=128), nullable=True),
    sa.Column('local_to_tag', sa.String(length=128), nullable=True),
    sa.Column('remote_contact', sa.String(length=512), nullable=True),
    sa.Column('record_route', sa.String(length=1024), nullable=True),
    sa.Column('notify_cseq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['parent_platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'event', name='uq_platform_subscriptions_platform_event')
    )
    op.create_index(op.f('ix_platform_subscriptions_created_at'), 'platform_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_subscriptions_event'), 'platform_subscriptions', ['event'], unique=False)
    op.create_index(op.f('ix_platform_subscriptions_expires_at'), 'platform_subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_platform_subscriptions_platform_id'), 'platform_subscriptions', ['platform_id'], unique=False)
    op.create_index(op.f('ix_platform_subscriptions_tenant_id'), 'platform_subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_platform_subscriptions_updated_at'), 'platform_subscriptions', ['updated_at'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('gb_id', sa.String(length=20), nullable=True, comment='通道国标ID'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='通道名称'),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True, comment='1: ON, 0: OFF'),
    sa.Column('has_audio', sa.Boolean(), nullable=True, comment='通道是否含音频，用于播放与对讲'),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('parent_gb_id', sa.String(length=20), nullable=True),
    sa.Column('region_parent_gb_id', sa.String(length=64), nullable=True),
    sa.Column('civil_code', sa.String(length=16), nullable=True),
    sa.Column('node_type', sa.String(length=16), nullable=True),
    sa.Column('numeric_channel_id', sa.Integer(), nullable=True, comment='numeric channel ID for fast lookup'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='安装地址'),
    sa.Column('parental', sa.Integer(), nullable=True, comment='是否有子设备: 0-无, 1-有'),
    sa.Column('safety_way', sa.Integer(), nullable=True, comment='安全模式'),
    sa.Column('register_way', sa.Integer(), nullable=True, comment='注册方式'),
    sa.Column('secrecy', sa.Integer(), nullable=True, comment='保密属性: 0-不涉密, 1-涉密'),
    sa.Column('ip_address', sa.String(length=64), nullable=True, comment='通道IP'),
    sa.Column('port', sa.Integer(), nullable=True, comment='通道端口'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='通道密码'),
    sa.Column('ptz_type', sa.Integer(), nullable=True, comment='PTZ类型: 0-未知, 1-球机, 2-半球, 3-固定枪机, 4-遥控枪机'),
    sa.Column('position_type', sa.Integer(), nullable=True, comment='安装位置: 0-未知, 1-室内, 2-室外'),
    sa.Column('room_type', sa.Integer(), nullable=True, comment='房间类型'),
    sa.Column('use_type', sa.Integer(), nullable=True, comment='用途类型'),
    sa.Column('supply_light_type', sa.Integer(), nullable=True, comment='补光类型'),
    sa.Column('direction_type', sa.Integer(), nullable=True, comment='摄像机方向'),
    sa.Column('resolution', sa.String(length=32), nullable=True, comment='分辨率'),
    sa.Column('business_group_id', sa.String(length=64), nullable=True, comment='业务组ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_asset_id'), 'resources', ['asset_id'], unique=False)
    op.create_index(op.f('ix_resources_civil_code'), 'resources', ['civil_code'], unique=False)
    op.create_index(op.f('ix_resources_gb_id'), 'resources', ['gb_id'], unique=False)
    op.create_index(op.f('ix_resources_node_type'), 'resources', ['node_type'], unique=False)
    op.create_index(op.f('ix_resources_numeric_channel_id'), 'resources', ['numeric_channel_id'], unique=False)
    op.create_index(op.f('ix_resources_parent_gb_id'), 'resources', ['parent_gb_id'], unique=False)
    op.create_index(op.f('ix_resources_region_parent_gb_id'), 'resources', ['region_parent_gb_id'], unique=False)
    op.create_index(op.f('ix_resources_tenant_id'), 'resources', ['tenant_id'], unique=False)
    op.create_table('alarm_escalations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('alarm_id', sa.String(length=32), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('escalation_count', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('ack_user_id', sa.String(length=32), nullable=True),
    sa.Column('ack_at', sa.DateTime(), nullable=True),
    sa.Column('last_escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ack_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_escalations_alarm_id'), 'alarm_escalations', ['alarm_id'], unique=True)
    op.create_index(op.f('ix_alarm_escalations_escalation_level'), 'alarm_escalations', ['escalation_level'], unique=False)
    op.create_index(op.f('ix_alarm_escalations_state'), 'alarm_escalations', ['state'], unique=False)
    op.create_table('push_channels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('stream_name', sa.String(length=128), nullable=False),
    sa.Column('push_key_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('hashed_push_key', sa.String(length=128), nullable=True),
    sa.Column('gb_enabled', sa.Boolean(), nullable=True),
    sa.Column('gb_resource_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gb_resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_channels_gb_resource_id'), 'push_channels', ['gb_resource_id'], unique=False)
    op.create_index(op.f('ix_push_channels_push_key_prefix'), 'push_channels', ['push_key_prefix'], unique=False)
    op.create_index(op.f('ix_push_channels_stream_name'), 'push_channels', ['stream_name'], unique=False)
    op.create_index(op.f('ix_push_channels_tenant_id'), 'push_channels', ['tenant_id'], unique=False)
    op.create_table('record_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False, comment='通道ID'),
    sa.Column('plan_type', sa.String(length=24), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('time_ranges', sa.Text(), nullable=True, comment='JSON array of {start,end,days}'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级，报警联动可高于定时'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_schedules_plan_type'), 'record_schedules', ['plan_type'], unique=False)
    op.create_index(op.f('ix_record_schedules_resource_id'), 'record_schedules', ['resource_id'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True, comment='Duration in seconds'),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('stream_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('record_app', sa.String(length=32), nullable=True),
    sa.Column('media_node_id', sa.String(length=32), nullable=True),
    sa.Column('zlm_file_path', sa.String(length=512), nullable=True),
    sa.Column('url_checked_at', sa.DateTime(), nullable=True),
    sa.Column('url_ok', sa.Boolean(), nullable=True),
    sa.Column('url_status_code', sa.Integer(), nullable=True),
    sa.Column('url_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_asset_id'), 'records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_records_media_node_id'), 'records', ['media_node_id'], unique=False)
    op.create_index(op.f('ix_records_record_app'), 'records', ['record_app'], unique=False)
    op.create_index(op.f('ix_records_resource_id'), 'records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_records_start_time'), 'records', ['start_time'], unique=False)
    op.create_index(op.f('ix_records_tenant_id'), 'records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_records_url_checked_at'), 'records', ['url_checked_at'], unique=False)
    op.create_index(op.f('ix_records_url_ok'), 'records', ['url_ok'], unique=False)
    op.create_table('stream_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('app', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=True),
    sa.Column('cascade_platform_id', sa.String(length=32), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('from_tag', sa.String(length=64), nullable=True),
    sa.Column('to_tag', sa.String(length=64), nullable=True),
    sa.Column('via_branch', sa.String(length=64), nullable=True),
    sa.Column('cseq', sa.Integer(), nullable=True),
    sa.Column('ssrc', sa.String(length=16), nullable=True),
    sa.Column('media_server_id', sa.String(length=32), nullable=True),
    sa.Column('media_ip', sa.String(length=64), nullable=True),
    sa.Column('media_port', sa.Integer(), nullable=True),
    sa.Column('media_port_lease_id', sa.String(length=32), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['cascade_platform_id'], ['parent_platforms.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_sessions_call_id'), 'stream_sessions', ['call_id'], unique=False)
    op.create_index(op.f('ix_stream_sessions_cascade_platform_id'), 'stream_sessions', ['cascade_platform_id'], unique=False)
    op.create_index(op.f('ix_stream_sessions_ssrc'), 'stream_sessions', ['ssrc'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('alarm_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('assignee_user_id', sa.String(length=32), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alarm_id'], ['alarms.id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_alarm_id'), 'work_orders', ['alarm_id'], unique=False)
    op.create_index(op.f('ix_work_orders_assignee_user_id'), 'work_orders', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_work_orders_category'), 'work_orders', ['category'], unique=False)
    op.create_index(op.f('ix_work_orders_created_by_user_id'), 'work_orders', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_tenant_id'), 'work_orders', ['tenant_id'], unique=False)
    op.create_table('device_record_download_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('stream_session_id', sa.String(length=32), nullable=True),
    sa.Column('call_id', sa.String(length=128), nullable=True),
    sa.Column('app', sa.String(length=64), nullable=False),
    sa.Column('stream', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=True),
    sa.Column('record_ids', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['stream_session_id'], ['stream_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_record_download_tasks_asset_id'), 'device_record_download_tasks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_call_id'), 'device_record_download_tasks', ['call_id'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_created_at'), 'device_record_download_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_resource_id'), 'device_record_download_tasks', ['resource_id'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_start_time'), 'device_record_download_tasks', ['start_time'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_status'), 'device_record_download_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_stream_session_id'), 'device_record_download_tasks', ['stream_session_id'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_tenant_id'), 'device_record_download_tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_device_record_download_tasks_updated_at'), 'device_record_download_tasks', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_record_download_tasks_updated_at'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_tenant_id'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_stream_session_id'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_status'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_start_time'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_resource_id'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_created_at'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_call_id'), table_name='device_record_download_tasks')
    op.drop_index(op.f('ix_device_record_download_tasks_asset_id'), table_name='device_record_download_tasks')
    op.drop_table('device_record_download_tasks')
    op.drop_index(op.f('ix_work_orders_tenant_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_created_by_user_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_category'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assignee_user_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_alarm_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_stream_sessions_ssrc'), table_name='stream_sessions')
    op.drop_index(op.f('ix_stream_sessions_cascade_platform_id'), table_name='stream_sessions')
    op.drop_index(op.f('ix_stream_sessions_call_id'), table_name='stream_sessions')
    op.drop_table('stream_sessions')
    op.drop_index(op.f('ix_records_url_ok'), table_name='records')
    op.drop_index(op.f('ix_records_url_checked_at'), table_name='records')
    op.drop_index(op.f('ix_records_tenant_id'), table_name='records')
    op.drop_index(op.f('ix_records_start_time'), table_name='records')
    op.drop_index(op.f('ix_records_resource_id'), table_name='records')
    op.drop_index(op.f('ix_records_record_app'), table_name='records')
    op.drop_index(op.f('ix_records_media_node_id'), table_name='records')
    op.drop_index(op.f('ix_records_asset_id'), table_name='records')
    op.drop_table('records')
    op.drop_index(op.f('ix_record_schedules_resource_id'), table_name='record_schedules')
    op.drop_index(op.f('ix_record_schedules_plan_type'), table_name='record_schedules')
    op.drop_table('record_schedules')
    op.drop_index(op.f('ix_push_channels_tenant_id'), table_name='push_channels')
    op.drop_index(op.f('ix_push_channels_stream_name'), table_name='push_channels')
    op.drop_index(op.f('ix_push_channels_push_key_prefix'), table_name='push_channels')
    op.drop_index(op.f('ix_push_channels_gb_resource_id'), table_name='push_channels')
    op.drop_table('push_channels')
    op.drop_index(op.f('ix_alarm_escalations_state'), table_name='alarm_escalations')
    op.drop_index(op.f('ix_alarm_escalations_escalation_level'), table_name='alarm_escalations')
    op.drop_index(op.f('ix_alarm_escalations_alarm_id'), table_name='alarm_escalations')
    op.drop_table('alarm_escalations')
    op.drop_index(op.f('ix_resources_tenant_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_region_parent_gb_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_parent_gb_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_numeric_channel_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_node_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_gb_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_civil_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_asset_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_platform_subscriptions_updated_at'), table_name='platform_subscriptions')
    op.drop_index(op.f('ix_platform_subscriptions_tenant_id'), table_name='platform_subscriptions')
    op.drop_index(op.f('ix_platform_subscriptions_platform_id'), table_name='platform_subscriptions')
    op.drop_index(op.f('ix_platform_subscriptions_expires_at'), table_name='platform_subscriptions')
    op.drop_index(op.f('ix_platform_subscriptions_event'), table_name='platform_subscriptions')
    op.drop_index(op.f('ix_platform_subscriptions_created_at'), table_name='platform_subscriptions')
    op.drop_table('platform_subscriptions')
    op.drop_index(op.f('ix_device_subscriptions_updated_at'), table_name='device_subscriptions')
    op.drop_index(op.f('ix_device_subscriptions_tenant_id'), table_name='device_subscriptions')
    op.drop_index(op.f('ix_device_subscriptions_created_at'), table_name='device_subscriptions')
    op.drop_index(op.f('ix_device_subscriptions_asset_id'), table_name='device_subscriptions')
    op.drop_table('device_subscriptions')
    op.drop_index(op.f('ix_asset_stream_policies_asset_id'), table_name='asset_stream_policies')
    op.drop_table('asset_stream_policies')
    op.drop_index(op.f('ix_asset_stream_health_asset_id'), table_name='asset_stream_health')
    op.drop_table('asset_stream_health')
    op.drop_index(op.f('ix_asset_maintenances_asset_id'), table_name='asset_maintenances')
    op.drop_table('asset_maintenances')
    op.drop_index(op.f('ix_alarms_time'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_tenant_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_status'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_device_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_channel_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_tenant_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_key_prefix'), table_name='user_api_keys')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_tenant_subscriptions_tenant_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_status'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_plan_code'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_machine_code'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_branding_tenant_id'), table_name='tenant_branding')
    op.drop_table('tenant_branding')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_structured_events_tenant_id'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_source_plugin'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_event_type'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_event_time'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_device_id'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_created_at'), table_name='structured_events')
    op.drop_index(op.f('ix_structured_events_channel_id'), table_name='structured_events')
    op.drop_table('structured_events')
    op.drop_index(op.f('ix_sip_trace_events_trace_id'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_tenant_id'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_platform_id'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_event'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_device_id'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_created_at'), table_name='sip_trace_events')
    op.drop_index(op.f('ix_sip_trace_events_channel_id'), table_name='sip_trace_events')
    op.drop_table('sip_trace_events')
    op.drop_index(op.f('ix_rtp_receive_tasks_updated_at'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_tenant_id'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_stream_id'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_status'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_node_id'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_lease_id'), table_name='rtp_receive_tasks')
    op.drop_index(op.f('ix_rtp_receive_tasks_created_at'), table_name='rtp_receive_tasks')
    op.drop_table('rtp_receive_tasks')
    op.drop_index(op.f('ix_roles_updated_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_regions_parent_id'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_record_schedule_runtimes_tenant_id'), table_name='record_schedule_runtimes')
    op.drop_index(op.f('ix_record_schedule_runtimes_schedule_id'), table_name='record_schedule_runtimes')
    op.drop_index(op.f('ix_record_schedule_runtimes_resource_id'), table_name='record_schedule_runtimes')
    op.drop_index(op.f('ix_record_schedule_runtimes_created_at'), table_name='record_schedule_runtimes')
    op.drop_table('record_schedule_runtimes')
    op.drop_index(op.f('ix_publish_records_publish_id'), table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_index(op.f('ix_plugin_orders_user_id'), table_name='plugin_orders')
    op.drop_index(op.f('ix_plugin_orders_tenant_id'), table_name='plugin_orders')
    op.drop_index(op.f('ix_plugin_orders_status'), table_name='plugin_orders')
    op.drop_index(op.f('ix_plugin_orders_plugin_id'), table_name='plugin_orders')
    op.drop_index(op.f('ix_plugin_orders_order_no'), table_name='plugin_orders')
    op.drop_table('plugin_orders')
    op.drop_index(op.f('ix_platform_runtimes_tenant_id'), table_name='platform_runtimes')
    op.drop_index(op.f('ix_platform_runtimes_platform_id'), table_name='platform_runtimes')
    op.drop_table('platform_runtimes')
    op.drop_index(op.f('ix_platform_catalog_resources_resource_id'), table_name='platform_catalog_resources')
    op.drop_index(op.f('ix_platform_catalog_resources_platform_id'), table_name='platform_catalog_resources')
    op.drop_table('platform_catalog_resources')
    op.drop_index(op.f('ix_parent_platforms_tenant_id'), table_name='parent_platforms')
    op.drop_table('parent_platforms')
    op.drop_index(op.f('ix_organizations_tenant_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_operation_audits_module'), table_name='operation_audits')
    op.drop_table('operation_audits')
    op.drop_index(op.f('ix_network_metrics_tenant_id'), table_name='network_metrics')
    op.drop_index(op.f('ix_network_metrics_metric'), table_name='network_metrics')
    op.drop_index(op.f('ix_network_metrics_created_at'), table_name='network_metrics')
    op.drop_table('network_metrics')
    op.drop_index(op.f('ix_media_port_leases_stream_session_id'), table_name='media_port_leases')
    op.drop_index(op.f('ix_media_port_leases_media_server_id'), table_name='media_port_leases')
    op.drop_table('media_port_leases')
    op.drop_table('media_nodes')
    op.drop_index(op.f('ix_map_config_tenant_id'), table_name='map_config')
    op.drop_table('map_config')
    op.drop_index(op.f('ix_ip_blacklist_ip'), table_name='ip_blacklist')
    op.drop_table('ip_blacklist')
    op.drop_index(op.f('ix_ffmpeg_cmds_updated_at'), table_name='ffmpeg_cmds')
    op.drop_index(op.f('ix_ffmpeg_cmds_tenant_id'), table_name='ffmpeg_cmds')
    op.drop_index(op.f('ix_ffmpeg_cmds_created_at'), table_name='ffmpeg_cmds')
    op.drop_table('ffmpeg_cmds')
    op.drop_index(op.f('ix_device_positions_time'), table_name='device_positions')
    op.drop_index(op.f('ix_device_positions_device_id'), table_name='device_positions')
    op.drop_index(op.f('ix_device_positions_channel_id'), table_name='device_positions')
    op.drop_table('device_positions')
    op.drop_index(op.f('ix_device_clusters_tenant_id'), table_name='device_clusters')
    op.drop_table('device_clusters')
    op.drop_index(op.f('ix_config_revisions_revision'), table_name='config_revisions')
    op.drop_table('config_revisions')
    op.drop_index(op.f('ix_config_drafts_draft_id'), table_name='config_drafts')
    op.drop_table('config_drafts')
    op.drop_index(op.f('ix_command_sessions_tenant_id'), table_name='command_sessions')
    op.drop_index(op.f('ix_command_sessions_status'), table_name='command_sessions')
    op.drop_index(op.f('ix_command_sessions_alarm_id'), table_name='command_sessions')
    op.drop_table('command_sessions')
    op.drop_index(op.f('ix_command_participants_user_id'), table_name='command_participants')
    op.drop_index(op.f('ix_command_participants_session_id'), table_name='command_participants')
    op.drop_table('command_participants')
    op.drop_index(op.f('ix_command_instructions_user_id'), table_name='command_instructions')
    op.drop_index(op.f('ix_command_instructions_session_id'), table_name='command_instructions')
    op.drop_table('command_instructions')
    op.drop_index(op.f('ix_cloud_clusters_tenant_id'), table_name='cloud_clusters')
    op.drop_index(op.f('ix_cloud_clusters_enabled'), table_name='cloud_clusters')
    op.drop_table('cloud_clusters')
    op.drop_index(op.f('ix_billing_plans_is_active'), table_name='billing_plans')
    op.drop_index(op.f('ix_billing_plans_code'), table_name='billing_plans')
    op.drop_table('billing_plans')
    op.drop_index(op.f('ix_assets_tenant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_organization_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_gb_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_app_logs_tenant_id'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_plugin_id'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_platform'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_log_type'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_created_at'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_app_version'), table_name='app_logs')
    op.drop_table('app_logs')
    op.drop_index(op.f('ix_alarm_notifications_tenant_id'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_status'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_sent_at'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_device_id'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_channel_id'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_channel'), table_name='alarm_notifications')
    op.drop_index(op.f('ix_alarm_notifications_alarm_id'), table_name='alarm_notifications')
    op.drop_table('alarm_notifications')
    op.drop_index(op.f('ix_alarm_link_rules_tenant_id'), table_name='alarm_link_rules')
    op.drop_index(op.f('ix_alarm_link_rules_organization_id'), table_name='alarm_link_rules')
    op.drop_index(op.f('ix_alarm_link_rules_enabled'), table_name='alarm_link_rules')
    op.drop_table('alarm_link_rules')
    op.drop_index(op.f('ix_access_sources_tenant_id'), table_name='access_sources')
    op.drop_index(op.f('ix_access_sources_protocol'), table_name='access_sources')
    op.drop_index(op.f('ix_access_sources_gb_resource_id'), table_name='access_sources')
    op.drop_index(op.f('ix_access_sources_gb_id'), table_name='access_sources')
    op.drop_index(op.f('ix_access_sources_gb_enabled'), table_name='access_sources')
    op.drop_index(op.f('ix_access_sources_enabled'), table_name='access_sources')
    op.drop_table('access_sources')
    # ### end Alembic commands ###
