{{- if and .Values.persistence.backendData.enabled (not .Values.persistence.backendData.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pygbsentry.fullname" . }}-data
  labels:
    {{- include "pygbsentry.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.backendData.storageClassName }}
  storageClassName: {{ .Values.persistence.backendData.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backendData.size | quote }}
{{- end }}
---
{{- if and .Values.persistence.recordings.enabled (not .Values.persistence.recordings.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pygbsentry.fullname" . }}-recordings
  labels:
    {{- include "pygbsentry.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.recordings.storageClassName }}
  storageClassName: {{ .Values.persistence.recordings.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.recordings.size | quote }}
{{- end }}
