apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pygbsentry.fullname" . }}-secret
  labels:
    {{- include "pygbsentry.labels" . | nindent 4 }}
  annotations:
    # FIXED-P1: S-25 标记helm-resource-policy为keep，防止helm upgrade时Secret被重建导致JWT全部失效
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.backend.env.POSTGRES_PASSWORD | default (randAlphaNum 24) | quote }}
  REDIS_PASSWORD: {{ .Values.backend.env.REDIS_PASSWORD | default (randAlphaNum 24) | quote }}
  SECRET_KEY: {{ randAlphaNum 64 | quote }}
  MEDIA_SERVER_SECRET: {{ randAlphaNum 32 | quote }}
